"use client";
import { useState } from "react";
import { ArrowUpRight, CalendarDays, CheckCircle2, Clock3, Filter, GripVertical, LayoutDashboard, List, Search, Sparkles, X } from "lucide-react";

type Lead={id:number,name:string,handle:string,status:string,note:string,due?:string};
const statuses=["To Contact","Messaged","Follow Up","Replied","Interested","Applied","Joined"];
const seed:Lead[]=[
 {id:1,name:"Maha Yoga Studio",handle:"@mahayogaphilly",status:"Follow Up",note:"Asked for the media kit",due:"Today"},
 {id:2,name:"Grounded Wellness",handle:"hello@grounded.co",status:"Interested",note:"Wants September details"},
 {id:3,name:"Lumina Pilates",handle:"@luminapilates",status:"To Contact",note:"New Rittenhouse studio"},
 {id:4,name:"Soft Space Ceramics",handle:"@softspacephl",status:"Messaged",note:"Sent directory invitation"},
 {id:5,name:"Nia Rivers",handle:"@niamoves",status:"Replied",note:"Circle back after launch",due:"Sep 8"},
 {id:6,name:"Root & Rise",handle:"@rootandrise",status:"Applied",note:"Application received"},
 {id:7,name:"Philadelphia Movement",handle:"@phillymovement",status:"Joined",note:"Profile is live"},
];
const nav=["Overview","The Daily Session","The Healing Directory","Follow ups","Tasks","Hours","Settings"];

export default function Home(){
 const [view,setView]=useState("Overview"); const [leads,setLeads]=useState(seed); const [modal,setModal]=useState(false);
 const [tasks,setTasks]=useState([{name:"Follow up with THD applicants",meta:"High priority · Due today",done:false},{name:"Reach out to 15 TDS studios",meta:"Normal · 9 of 15 complete",done:false},{name:"Research five Philly events",meta:"Normal · Due Friday",done:true}]);
 const addLead=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setLeads([...leads,{id:Date.now(),name:String(f.get("name")),handle:String(f.get("contact")),status:String(f.get("status")),note:String(f.get("note"))}]);setModal(false)};
 return <main className="app-shell"><aside className="sidebar"><div className="brand-mark"><span>O</span><div><strong>Outreach</strong><small>WORKROOM</small></div></div><nav>{nav.map(item=><button onClick={()=>setView(item)} className={view===item?"active":""} key={item}>{item}</button>)}</nav><div className="sidebar-note"><Sparkles size={18}/><p><strong>Everything in motion.</strong><br/>A calm home for the work.</p></div><div className="profile"><span>TW</span><div><strong>Tiffany</strong><small>Workspace owner</small></div></div></aside><section className="workspace">{view==="Overview"?<Dashboard open={(v)=>setView(v)}/>:view==="Tasks"?<Tasks tasks={tasks} setTasks={setTasks}/>:view==="Hours"?<Hours/>:view==="Settings"?<Settings/>:<Outreach title={view} leads={leads} setLeads={setLeads} add={()=>setModal(true)}/>}</section>{modal&&<AddModal close={()=>setModal(false)} submit={addLead}/>}</main>
}

function Header({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action?:React.ReactNode}){return <header><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>}
function Dashboard({open}:{open:(v:string)=>void}){const stats=[["To contact","38"],["Messaged","24"],["Needs follow up","7"],["Interested","11"],["Joined","18"]];return <><Header eyebrow="THURSDAY · SEPTEMBER 3" title="Good evening, Tiffany." sub="Here’s what’s moving across both brands." action={<div className="header-actions"><button className="icon-button"><Search size={18}/></button><button className="primary" onClick={()=>open("The Daily Session")}>+ Add account</button></div>}/><div className="status-strip">{stats.map(([label,value])=><button key={label} onClick={()=>open(label==="Needs follow up"?"Follow ups":"The Daily Session")}><span>{value}</span><small>{label}</small><ArrowUpRight size={14}/></button>)}</div><div className="dashboard-grid"><section className="priority-card dark"><div className="card-head"><div><p className="eyebrow coral">TODAY’S FOCUS</p><h2>Keep the warm leads warm.</h2></div><span>7 open</span></div><div className="focus-row"><div><strong>4</strong><small>Follow ups due today</small></div><button onClick={()=>open("Follow ups")}>Start follow ups <ArrowUpRight size={16}/></button></div><div className="focus-meta"><span><Clock3 size={15}/> 2 overdue</span><span><CalendarDays size={15}/> 5 this week</span></div></section><section className="week-card"><div className="card-head"><div><p className="eyebrow">THIS WEEK</p><h2>4 tasks remaining</h2></div><span className="progress">3 of 7</span></div><div className="task"><i className="high"/><div><strong>Follow up with THD applicants</strong><small>High priority · Due today</small></div></div><div className="task"><i/><div><strong>Reach out to 15 TDS studios</strong><small>Normal · 9 of 15 complete</small></div></div><button className="text-link" onClick={()=>open("Tasks")}>View all tasks →</button></section><Brand initials="DS" label="THE DAILY SESSION" title="Studio outreach" metrics={["21","6","3"]} open={()=>open("The Daily Session")}/><Brand initials="HD" label="THE HEALING DIRECTORY" title="Provider outreach" metrics={["44","5","4"]} accent open={()=>open("The Healing Directory")}/><section className="anytime"><div><CheckCircle2 size={20}/><div><p className="eyebrow">EXTRA TIME?</p><h3>There’s always something useful to pick up.</h3></div></div><button onClick={()=>open("Tasks")}>Browse anytime tasks →</button></section></div></>}
function Brand({initials,label,title,metrics,accent=false,open}:{initials:string,label:string,title:string,metrics:string[],accent?:boolean,open:()=>void}){return <section className={`brand-card ${accent?"accent":""}`}><div className="brand-icon">{initials}</div><p className="eyebrow">{label}</p><h2>{title}</h2><div className="brand-metrics">{metrics.map((x,i)=><div key={i}><strong>{x}</strong><small>{["Accounts","Interested","Due"][i]}</small></div>)}</div><button onClick={open}>Open outreach <ArrowUpRight size={15}/></button></section>}

function Outreach({title,leads,setLeads,add}:{title:string,leads:Lead[],setLeads:(x:Lead[])=>void,add:()=>void}){const [mode,setMode]=useState("Pipeline");const shown=title==="Follow ups"?leads.filter(x=>x.status==="Follow Up"):leads;const move=(id:number,status:string)=>setLeads(leads.map(x=>x.id===id?{...x,status}:x));return <><Header eyebrow={title==="Follow ups"?"DUE & OVERDUE":"OUTREACH PIPELINE"} title={title==="Follow ups"?"Follow ups":`${title} Outreach`} sub={title==="Follow ups"?"The conversations that need a gentle nudge.":"Move quickly, keep notes short, and never lose the thread."} action={<button className="primary" onClick={add}>+ Add account</button>}/><div className="toolbar"><label><Search size={16}/><input placeholder="Search accounts…"/></label><button><Filter size={15}/> Filter</button><div className="segmented"><button className={mode==="Pipeline"?"selected":""} onClick={()=>setMode("Pipeline")}><LayoutDashboard size={14}/> Pipeline</button><button className={mode==="Table"?"selected":""} onClick={()=>setMode("Table")}><List size={14}/> Table</button></div></div>{mode==="Pipeline"?<div className="pipeline">{statuses.map(status=><section className="column" key={status} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData("id")),status)}><div className="column-head"><strong>{status}</strong><span>{shown.filter(x=>x.status===status).length}</span></div>{shown.filter(x=>x.status===status).map(lead=><article draggable onDragStart={e=>e.dataTransfer.setData("id",String(lead.id))} className="lead-card" key={lead.id}><GripVertical size={14}/><strong>{lead.name}</strong><small>{lead.handle}</small>{lead.due&&<em className={lead.due==="Today"?"overdue":""}>Follow up: {lead.due}</em>}<p>“{lead.note}”</p></article>)}</section>)}</div>:<div className="table-wrap"><table><thead><tr>{["Account","Instagram / Email","Status","Follow Up","Notes","Added By"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.handle}</td><td><select value={x.status} onChange={e=>move(x.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{x.due||"—"}</td><td>{x.note}</td><td>Assistant</td></tr>)}</tbody></table></div>}</>}

function Tasks({tasks,setTasks}:{tasks:{name:string,meta:string,done:boolean}[],setTasks:(x:{name:string,meta:string,done:boolean}[])=>void}){const [newTask,setNewTask]=useState("");const add=()=>{if(newTask){setTasks([...tasks,{name:newTask,meta:"Normal · This week",done:false}]);setNewTask("")}};return <><Header eyebrow="WEEK OF AUGUST 31" title="Tasks & responsibilities" sub="Weekly priorities first. Useful backup work is always waiting." action={<button className="primary" onClick={add}>+ Add weekly task</button>}/><div className="week-nav"><button>← Previous week</button><strong>This week</strong><button>Next week →</button></div><div className="tasks-grid"><section className="task-panel"><div className="section-title"><div><p className="eyebrow">THIS WEEK</p><h2>{tasks.filter(x=>x.done).length} of {tasks.length} completed</h2></div><span>{Math.round(tasks.filter(x=>x.done).length/tasks.length*100)}%</span></div><div className="task-progress"><i style={{width:`${tasks.filter(x=>x.done).length/tasks.length*100}%`}}/></div><div className="quick-add"><input value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="Add a responsibility…" onKeyDown={e=>e.key==="Enter"&&add()}/><button onClick={add}>Add</button></div>{tasks.map((t,i)=><button className={`task-row ${t.done?"done":""}`} key={t.name} onClick={()=>setTasks(tasks.map((x,j)=>j===i?{...x,done:!x.done}:x))}><span>{t.done?"✓":""}</span><div><strong>{t.name}</strong><small>{t.meta}</small></div><b>•••</b></button>)}</section><section className="task-panel anytime-panel"><div className="section-title"><div><p className="eyebrow coral">ANYTIME TASKS</p><h2>Finished the priorities?</h2></div></div><p className="helper">Pick something from here. These stay available after each work session.</p>{["Find new TDS studios","Research new THD providers","Engage with target accounts","Look for local event ideas"].map((x,i)=><article className="any-task" key={x}><div><strong>{x}</strong><small>{["30 min · The Daily Session","Open ended · Healing Directory","15 min · Both brands","30 min · The Daily Session"][i]}</small></div><button>Work on this</button></article>)}</section></div></>}
function Hours(){return <><Header eyebrow="TIME & ACTIVITY" title="Hours" sub="A simple record of focused work across both brands." action={<button className="primary">Start timer</button>}/><div className="hours-summary"><div><small>THIS WEEK</small><strong>12h 30m</strong></div><div><small>THE DAILY SESSION</small><strong>6h 45m</strong></div><div><small>HEALING DIRECTORY</small><strong>5h 45m</strong></div></div><section className="log-card"><div className="section-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Time log</h2></div><button>+ Add hours</button></div>{[["Sep 3","TDS outreach","2h 15m"],["Sep 2","THD follow ups","1h 30m"],["Sep 1","Research + engagement","3h 00m"],["Aug 31","Weekly planning","1h 15m"]].map(x=><div className="log-row" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><em>{x[2]}</em><b>Approved</b></div>)}</section></>}
function Settings(){return <><Header eyebrow="WORKSPACE" title="Settings" sub="The little rules that keep the workroom running itself."/><div className="settings-card"><div><h3>Automatically create standard weekly tasks</h3><p>Start every Monday with the baseline assistant responsibilities already assigned.</p></div><button className="switch on"><i/></button></div><div className="settings-card"><div><h3>Weekly task template</h3><p>TDS outreach, THD outreach, follow ups, engagement, and new prospect research.</p></div><button>Edit template</button></div><div className="settings-card"><div><h3>Team</h3><p>Tiffany · Owner &nbsp;&nbsp; Assistant · Collaborator</p></div><button>Manage</button></div></>}
function AddModal({close,submit}:{close:()=>void,submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={close}><X size={18}/></button><p className="eyebrow">NEW OUTREACH ACCOUNT</p><h2>Add someone to the pipeline</h2><label>Account name<input name="name" required placeholder="Maha Yoga Studio"/></label><label>Instagram or email<input name="contact" placeholder="@handle or email"/></label><div className="form-grid"><label>Account type<select><option>Studio / Business</option><option>Provider</option><option>Instructor / Creator</option><option>Partner / Organization</option></select></label><label>Status<select name="status">{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Quick note<textarea name="note" placeholder="Anything helpful for the next touchpoint…"/></label><button className="primary" type="submit">Add account</button></form></div>}
