"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, AtSign as Instagram, CalendarDays, CheckCircle2, Clock3, Filter, GripVertical, LayoutDashboard, List, Mail, Plus, Search, Sparkles, UserRound, X } from "lucide-react";

type Update={text:string,date:string,by:string};
type ContactTask={text:string,due:string,done:boolean};
type Lead={id:number;name:string;handle:string;email?:string;brand:string;type:string;status:string;note:string;due?:string;addedBy:string;updates:Update[];tasks:ContactTask[]};
const statuses=["To Contact","Messaged","Follow Up","Replied","Interested","Applied","Joined"];
const seed:Lead[]=[
 {id:1,name:"Maha Yoga Studio",handle:"@mahayogaphilly",email:"hello@mahayoga.com",brand:"The Daily Session",type:"Studio / Business",status:"Follow Up",note:"Asked for the media kit",due:"Today",addedBy:"Tiffany",updates:[{text:"Sent the fall partnership overview.",date:"Sep 2 · 4:30 PM",by:"Assistant"}],tasks:[{text:"Send the studio link",due:"Today",done:false}]},
 {id:2,name:"Grounded Wellness",handle:"@groundedwellness",email:"hello@grounded.co",brand:"The Healing Directory",type:"Provider",status:"Interested",note:"Wants September details",addedBy:"Assistant",updates:[],tasks:[]},
 {id:3,name:"Lumina Pilates",handle:"@luminapilates",brand:"The Daily Session",type:"Studio / Business",status:"To Contact",note:"New Rittenhouse studio",addedBy:"Assistant",updates:[],tasks:[]},
 {id:4,name:"Soft Space Ceramics",handle:"@softspacephl",brand:"The Daily Session",type:"Studio / Business",status:"Messaged",note:"Sent directory invitation",addedBy:"Tiffany",updates:[],tasks:[]},
 {id:5,name:"Nia Rivers",handle:"@niamoves",brand:"The Healing Directory",type:"Instructor / Creator",status:"Replied",note:"Circle back after launch",due:"Sep 8",addedBy:"Assistant",updates:[],tasks:[{text:"First follow up",due:"Sep 8",done:false}]},
 {id:6,name:"Root & Rise",handle:"@rootandrise",brand:"The Healing Directory",type:"Provider",status:"Applied",note:"Application received",addedBy:"Tiffany",updates:[],tasks:[]},
 {id:7,name:"Philadelphia Movement",handle:"@phillymovement",brand:"The Daily Session",type:"Studio / Business",status:"Joined",note:"Profile is live",addedBy:"Assistant",updates:[],tasks:[]},
];
const nav=["Overview","Pipeline","Contacts","Follow ups","Tasks","Hours","Settings"];

export default function Home(){
 const [view,setView]=useState("Overview"),[leads,setLeads]=useState<Lead[]>(seed),[addOpen,setAddOpen]=useState(false),[selected,setSelected]=useState<number|null>(null),[ready,setReady]=useState(false);
 const [tasks,setTasks]=useState([{name:"Follow up with THD applicants",meta:"High priority · Due today",done:false},{name:"Reach out to 15 TDS studios",meta:"Normal · 9 of 15 complete",done:false},{name:"Research five Philly events",meta:"Normal · Due Friday",done:true}]);
 useEffect(()=>{try{const saved=localStorage.getItem("outreach-workroom-contacts");if(saved){const parsed=JSON.parse(saved);if(Array.isArray(parsed))setLeads(parsed)}}catch{}finally{setReady(true)}},[]);
 useEffect(()=>{if(!ready)return;localStorage.setItem("outreach-workroom-contacts",JSON.stringify(leads))},[leads,ready]);
 const addLead=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const lead:Lead={id:Date.now(),name:String(f.get("name")),handle:String(f.get("instagram")||""),email:String(f.get("email")||""),brand:String(f.get("brand")),type:String(f.get("type")),status:String(f.get("status")),due:String(f.get("due")||""),note:String(f.get("note")||""),addedBy:"Tiffany",updates:[],tasks:[]};setLeads([lead,...leads]);setAddOpen(false);setSelected(lead.id);setView("Contacts")};
 const changeLead=(next:Lead)=>setLeads(leads.map(x=>x.id===next.id?next:x));
 return <main className="app-shell"><aside className="sidebar"><div className="brand-mark"><span>O</span><div><strong>Outreach</strong><small>WORKROOM</small></div></div><button className="sidebar-add" onClick={()=>setAddOpen(true)}><Plus size={17}/> Add contact</button><nav>{nav.map(item=><button onClick={()=>setView(item)} className={view===item?"active":""} key={item}>{item}</button>)}</nav><div className="sidebar-note"><Sparkles size={18}/><p><strong>Everything in motion.</strong><br/>A calm home for the work.</p></div><div className="profile"><span>TW</span><div><strong>Tiffany</strong><small>Workspace owner</small></div></div></aside><section className="workspace">{view==="Overview"?<Dashboard leads={leads} open={setView} add={()=>setAddOpen(true)}/>:view==="Contacts"?<Contacts leads={leads} open={setSelected} add={()=>setAddOpen(true)}/>:view==="Tasks"?<Tasks tasks={tasks} setTasks={setTasks}/>:view==="Hours"?<Hours/>:view==="Settings"?<Settings/>:<Outreach title={view} leads={leads} setLeads={setLeads} add={()=>setAddOpen(true)} open={setSelected}/>}</section><button className="floating-add" onClick={()=>setAddOpen(true)}><Plus size={20}/><span>Add contact</span></button>{addOpen&&<AddModal close={()=>setAddOpen(false)} submit={addLead}/>} {selected&&<ContactDetail lead={leads.find(x=>x.id===selected)!} change={changeLead} close={()=>setSelected(null)}/>}</main>
}
function Header({eyebrow,title,sub,action}:{eyebrow:string,title:string,sub:string,action?:React.ReactNode}){return <header><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{sub}</p></div>{action}</header>}
function Dashboard({leads,open,add}:{leads:Lead[],open:(v:string)=>void,add:()=>void}){const count=(s:string)=>leads.filter(x=>x.status===s).length;return <><Header eyebrow="THURSDAY · SEPTEMBER 3" title="Good evening, Tiffany." sub="Here’s what’s moving across both brands." action={<button className="primary add-prominent" onClick={add}><Plus size={17}/> Add contact</button>}/><div className="status-strip">{[["To contact",count("To Contact")],["Messaged",count("Messaged")],["Needs follow up",count("Follow Up")],["Interested",count("Interested")],["Joined",count("Joined")]].map(([label,value])=><button key={label} onClick={()=>open(label==="Needs follow up"?"Follow ups":"Pipeline")}><span>{value}</span><small>{label}</small><ArrowUpRight size={14}/></button>)}</div><div className="dashboard-grid"><section className="priority-card dark"><div className="card-head"><div><p className="eyebrow coral">TODAY’S FOCUS</p><h2>Keep the warm leads warm.</h2></div><span>{count("Follow Up")} open</span></div><div className="focus-row"><div><strong>{count("Follow Up")}</strong><small>Follow ups waiting</small></div><button onClick={()=>open("Follow ups")}>Start follow ups <ArrowUpRight size={16}/></button></div><div className="focus-meta"><span><Clock3 size={15}/> Nothing gets lost</span><span><CalendarDays size={15}/> One shared queue</span></div></section><section className="week-card"><div className="card-head"><div><p className="eyebrow">THIS WEEK</p><h2>4 tasks remaining</h2></div><span className="progress">3 of 7</span></div><div className="task"><i className="high"/><div><strong>Follow up with THD applicants</strong><small>High priority · Due today</small></div></div><div className="task"><i/><div><strong>Reach out to 15 TDS studios</strong><small>Normal · 9 of 15 complete</small></div></div><button className="text-link" onClick={()=>open("Tasks")}>View all tasks →</button></section><Brand initials="DS" label="THE DAILY SESSION" title="Studio outreach" leads={leads.filter(x=>x.brand==="The Daily Session")} open={()=>open("Pipeline")}/><Brand initials="HD" label="THE HEALING DIRECTORY" title="Provider outreach" leads={leads.filter(x=>x.brand==="The Healing Directory")} accent open={()=>open("Pipeline")}/><section className="anytime"><div><CheckCircle2 size={20}/><div><p className="eyebrow">EXTRA TIME?</p><h3>There’s always something useful to pick up.</h3></div></div><button onClick={()=>open("Tasks")}>Browse anytime tasks →</button></section></div></>}
function Brand({initials,label,title,leads,accent=false,open}:{initials:string,label:string,title:string,leads:Lead[],accent?:boolean,open:()=>void}){return <section className={`brand-card ${accent?"accent":""}`}><div className="brand-icon">{initials}</div><p className="eyebrow">{label}</p><h2>{title}</h2><div className="brand-metrics"><div><strong>{leads.length}</strong><small>Contacts</small></div><div><strong>{leads.filter(x=>x.status==="Interested").length}</strong><small>Interested</small></div><div><strong>{leads.filter(x=>x.status==="Follow Up").length}</strong><small>Due</small></div></div><button onClick={open}>Open pipeline <ArrowUpRight size={15}/></button></section>}

function Outreach({title,leads,setLeads,add,open}:{title:string,leads:Lead[],setLeads:(x:Lead[])=>void,add:()=>void,open:(id:number)=>void}){const [mode,setMode]=useState("Pipeline"),[brand,setBrand]=useState("All");const filtered=leads.filter(x=>(brand==="All"||x.brand===brand)&&(title!=="Follow ups"||x.status==="Follow Up"));const move=(id:number,status:string)=>setLeads(leads.map(x=>x.id===id?{...x,status}:x));return <><Header eyebrow={title==="Follow ups"?"DUE & OVERDUE":"OUTREACH"} title={title==="Follow ups"?"Follow ups":"Outreach pipeline"} sub="The full path from first find to joined—without sales clutter." action={<button className="primary add-prominent" onClick={add}><Plus size={17}/> Add contact</button>}/><div className="toolbar"><label><Search size={16}/><input placeholder="Search contacts…"/></label><select value={brand} onChange={e=>setBrand(e.target.value)}><option>All</option><option>The Daily Session</option><option>The Healing Directory</option></select><button><Filter size={15}/> Filter</button><div className="segmented"><button className={mode==="Pipeline"?"selected":""} onClick={()=>setMode("Pipeline")}><LayoutDashboard size={14}/> Pipeline</button><button className={mode==="Table"?"selected":""} onClick={()=>setMode("Table")}><List size={14}/> List</button></div></div>{mode==="Pipeline"?<div className="pipeline">{statuses.map(status=><section className="column" key={status} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData("id")),status)}><div className="column-head"><strong>{status}</strong><span>{filtered.filter(x=>x.status===status).length}</span><button onClick={add}><Plus size={15}/></button></div>{filtered.filter(x=>x.status===status).map(lead=><article draggable onDragStart={e=>e.dataTransfer.setData("id",String(lead.id))} onClick={()=>open(lead.id)} className="lead-card" key={lead.id}><GripVertical size={14}/><strong>{lead.name}</strong><small>{lead.handle||lead.email}</small>{lead.due&&<em className={lead.due==="Today"?"overdue":""}>Follow up: {lead.due}</em>}<p>“{lead.note}”</p></article>)}</section>)}</div>:<ContactTable leads={filtered} open={open} move={move}/>}</>}
function Contacts({leads,open,add}:{leads:Lead[],open:(id:number)=>void,add:()=>void}){const [q,setQ]=useState(""),[brand,setBrand]=useState("All");const shown=useMemo(()=>leads.filter(x=>(brand==="All"||x.brand===brand)&&(`${x.name} ${x.handle} ${x.email}`.toLowerCase().includes(q.toLowerCase()))),[leads,q,brand]);return <><Header eyebrow="PEOPLE & PLACES" title="Contacts" sub="Every studio, provider, creator, and partner in one clean home." action={<button className="primary add-prominent" onClick={add}><Plus size={17}/> Add contact</button>}/><div className="contact-toolbar"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, Instagram, or email…"/></label><select value={brand} onChange={e=>setBrand(e.target.value)}><option>All</option><option>The Daily Session</option><option>The Healing Directory</option></select><span>{shown.length} contacts</span></div><div className="contact-list"><div className="contact-list-head"><span>Contact</span><span>Brand</span><span>Stage</span><span>Follow up</span><span>Added by</span></div>{shown.map(x=><button className="contact-list-row" key={x.id} onClick={()=>open(x.id)}><span className="contact-person"><i>{x.name.slice(0,2).toUpperCase()}</i><span><strong>{x.name}</strong><small>{x.handle||x.email}</small></span></span><span><b className={`brand-pill ${x.brand.includes("Healing")?"thd":""}`}>{x.brand.includes("Healing")?"THD":"TDS"}</b></span><span><b className="stage-pill">{x.status}</b></span><span>{x.due||"—"}</span><span>{x.addedBy}</span></button>)}</div></>}
function ContactTable({leads,open,move}:{leads:Lead[],open:(id:number)=>void,move:(id:number,s:string)=>void}){return <div className="table-wrap"><table><thead><tr>{["Contact","Instagram / Email","Brand","Stage","Follow Up","Added By"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{leads.map(x=><tr key={x.id} onClick={()=>open(x.id)}><td><strong>{x.name}</strong></td><td>{x.handle||x.email}</td><td>{x.brand}</td><td><select value={x.status} onClick={e=>e.stopPropagation()} onChange={e=>move(x.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td>{x.due||"—"}</td><td>{x.addedBy}</td></tr>)}</tbody></table></div>}

function ContactDetail({lead,change,close}:{lead:Lead,change:(x:Lead)=>void,close:()=>void}){const [update,setUpdate]=useState(""),[task,setTask]=useState("");const addUpdate=()=>{if(!update.trim())return;change({...lead,updates:[{text:update,date:"Just now",by:"Tiffany"},...lead.updates]});setUpdate("")};const addTask=()=>{if(!task.trim())return;change({...lead,tasks:[...lead.tasks,{text:task,due:"Tomorrow",done:false}]});setTask("")};return <div className="detail-backdrop" onMouseDown={close}><section className="contact-detail" onMouseDown={e=>e.stopPropagation()}><header className="detail-title"><div><span>{lead.name.slice(0,2).toUpperCase()}</span><div><h2>{lead.name}</h2><p>{lead.brand} · {lead.type}</p></div></div><button onClick={close}><X/></button></header><div className="detail-body"><main><div className="detail-fields"><label>Instagram<div><Instagram size={16}/><input value={lead.handle} onChange={e=>change({...lead,handle:e.target.value})}/></div></label><label>Email<div><Mail size={16}/><input value={lead.email||""} onChange={e=>change({...lead,email:e.target.value})}/></div></label><label>Stage<select value={lead.status} onChange={e=>change({...lead,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Follow-up date<input value={lead.due||""} onChange={e=>change({...lead,due:e.target.value})} placeholder="Sep 8"/></label></div><div className="detail-section"><div className="detail-section-title"><h3>Open tasks ({lead.tasks.filter(x=>!x.done).length})</h3></div><div className="inline-create"><input value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addTask()} placeholder="Add a follow-up task…"/><button onClick={addTask}>Add task</button></div>{lead.tasks.map((t,i)=><button className={`contact-task ${t.done?"done":""}`} key={i} onClick={()=>change({...lead,tasks:lead.tasks.map((x,j)=>j===i?{...x,done:!x.done}:x)})}><i>{t.done?"✓":""}</i><span><strong>{t.text}</strong><small>Due: {t.due}</small></span></button>)}</div><div className="detail-section"><h3>Activity</h3><article className="activity-card"><p>Contact added by {lead.addedBy}</p>{lead.updates.map((u,i)=><div key={i}><strong>{u.by}</strong> added an update · {u.date}<p>{u.text}</p></div>)}</article></div></main><aside className="updates"><div className="update-intro"><UserRound/><h3>Leave an update</h3><p>Share notes, progress, and keep everyone aligned on this contact.</p></div><div className="update-compose"><textarea value={update} onChange={e=>setUpdate(e.target.value)} placeholder="Leave an update…"/><button onClick={addUpdate}>Post update</button></div></aside></div></section></div>}

function Tasks({tasks,setTasks}:{tasks:{name:string,meta:string,done:boolean}[],setTasks:(x:{name:string,meta:string,done:boolean}[])=>void}){const [newTask,setNewTask]=useState("");const add=()=>{if(newTask){setTasks([...tasks,{name:newTask,meta:"Normal · This week",done:false}]);setNewTask("")}};return <><Header eyebrow="WEEK OF AUGUST 31" title="Tasks & responsibilities" sub="Weekly priorities first. Useful backup work is always waiting." action={<button className="primary" onClick={add}>+ Add weekly task</button>}/><div className="week-nav"><button>← Previous week</button><strong>This week</strong><button>Next week →</button></div><div className="tasks-grid"><section className="task-panel"><div className="section-title"><div><p className="eyebrow">THIS WEEK</p><h2>{tasks.filter(x=>x.done).length} of {tasks.length} completed</h2></div><span>{Math.round(tasks.filter(x=>x.done).length/tasks.length*100)}%</span></div><div className="task-progress"><i style={{width:`${tasks.filter(x=>x.done).length/tasks.length*100}%`}}/></div><div className="quick-add"><input value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="Add a responsibility…" onKeyDown={e=>e.key==="Enter"&&add()}/><button onClick={add}>Add</button></div>{tasks.map((t,i)=><button className={`task-row ${t.done?"done":""}`} key={t.name} onClick={()=>setTasks(tasks.map((x,j)=>j===i?{...x,done:!x.done}:x))}><span>{t.done?"✓":""}</span><div><strong>{t.name}</strong><small>{t.meta}</small></div><b>•••</b></button>)}</section><section className="task-panel anytime-panel"><div className="section-title"><div><p className="eyebrow coral">ANYTIME TASKS</p><h2>Finished the priorities?</h2></div></div><p className="helper">Pick something from here. These stay available after each work session.</p>{["Find new TDS studios","Research new THD providers","Engage with target accounts","Look for local event ideas"].map((x,i)=><article className="any-task" key={x}><div><strong>{x}</strong><small>{["30 min · The Daily Session","Open ended · Healing Directory","15 min · Both brands","30 min · The Daily Session"][i]}</small></div><button>Work on this</button></article>)}</section></div></>}
function Hours(){return <><Header eyebrow="TIME & ACTIVITY" title="Hours" sub="A simple record of focused work across both brands." action={<button className="primary">Start timer</button>}/><div className="hours-summary"><div><small>THIS WEEK</small><strong>12h 30m</strong></div><div><small>THE DAILY SESSION</small><strong>6h 45m</strong></div><div><small>HEALING DIRECTORY</small><strong>5h 45m</strong></div></div><section className="log-card"><div className="section-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Time log</h2></div><button>+ Add hours</button></div>{[["Sep 3","TDS outreach","2h 15m"],["Sep 2","THD follow ups","1h 30m"],["Sep 1","Research + engagement","3h 00m"],["Aug 31","Weekly planning","1h 15m"]].map(x=><div className="log-row" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><em>{x[2]}</em><b>Approved</b></div>)}</section></>}
function Settings(){return <><Header eyebrow="WORKSPACE" title="Settings" sub="The little rules that keep the workroom running itself."/><div className="settings-card"><div><h3>Automatically create standard weekly tasks</h3><p>Start every Monday with the baseline assistant responsibilities already assigned.</p></div><button className="switch on"><i/></button></div><div className="settings-card"><div><h3>Weekly task template</h3><p>TDS outreach, THD outreach, follow ups, engagement, and new prospect research.</p></div><button>Edit template</button></div><div className="settings-card"><div><h3>Team</h3><p>Tiffany · Owner &nbsp;&nbsp; Assistant · Collaborator</p></div><button>Manage</button></div></>}
function AddModal({close,submit}:{close:()=>void,submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop" onMouseDown={close}><form className="modal quick-contact" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={close}><X size={18}/></button><p className="eyebrow">NEW CONTACT</p><h2>Add someone in seconds</h2><p className="modal-helper">Name is the only required field. You can fill in the rest later.</p><label>Contact or account name<input name="name" required autoFocus placeholder="Maha Yoga Studio"/></label><div className="form-grid"><label>Instagram<input name="instagram" placeholder="@handle"/></label><label>Email<input name="email" type="email" placeholder="hello@studio.com"/></label><label>Brand<select name="brand"><option>The Daily Session</option><option>The Healing Directory</option></select></label><label>Type<select name="type"><option>Studio / Business</option><option>Provider</option><option>Instructor / Creator</option><option>Partner / Organization</option><option>Other</option></select></label><label>Stage<select name="status">{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Follow-up date<input name="due" placeholder="Sep 8"/></label></div><label>Quick note<textarea name="note" placeholder="Anything helpful for the next touchpoint…"/></label><button className="primary" type="submit"><Plus size={17}/> Add contact</button></form></div>}
